# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d2c16c78bffd93747e2068246dbb0cf21913317e81c2e71a09381a929f6602ae24772e92e3135eb6724c9fba742ffa9fbb4b535d75c8f0ae406c7e16b46aefb

test:
  secret_key_base: 3229aa90273a9b6239c2af5d8ce303e23aacb0164f022d74f65d55f4900bd75022360734b6948ef3bb6648fcbd9a456a6f3625e792779a39395e87cd88a93dd7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
